name: Minify

on: 
  push:
    branches: [master]
  pull_request:
    branches: [master, staging]

jobs:
  read:
    runs-on: ubuntu-20.04

    steps:
  # Checks-out your repository under $GITHUB_WORKSPACE, so auto-minify job can access it
      - name: Checkout Step
        uses: actions/checkout@v2

      - name: Auto Minify
        uses: nizarmah/auto-minify@master

      # Auto commits minified files to the repository
      # Ignore it if you don't want to commit the files to the repository 
      - name: Auto committing minified files
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Github Action: Auto Minified JS and CSS files"
          branch: staging
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 